export default {
  "back": require("src/assets/cards/purple-back.png"),
  "blue1": require("src/assets/cards/blue-one.png"),
  "blue2": require("src/assets/cards/blue-two.png"),
  "blue3": require("src/assets/cards/blue-three.png"),
  "blue4": require("src/assets/cards/blue-four.png"),
  "blue5": require("src/assets/cards/blue-five.png"),
  "blue6": require("src/assets/cards/blue-six.png"),
  "grey": require("src/assets/cards/grey-back.png"),
  "green1": require("src/assets/cards/green-one.png"),
  "green2": require("src/assets/cards/green-two.png"),
  "green3": require("src/assets/cards/green-three.png"),
  "green4": require("src/assets/cards/green-four.png"),
  "green5": require("src/assets/cards/green-five.png"),
  "green6": require("src/assets/cards/green-six.png"),
  "green7": require("src/assets/cards/green-seven.png"),
  "green8": require("src/assets/cards/green-eight.png"),
  "green9": require("src/assets/cards/green-nine.png"),
  "green10": require("src/assets/cards/green-ten.png"),
  "placeholder": require("src/assets/cards/placeholder.png"),
  "red-1": require("src/assets/cards/red-one.png"),
  "red-2": require("src/assets/cards/red-two.png"),
  "red-3": require("src/assets/cards/red-three.png"),
  "red-4": require("src/assets/cards/red-four.png"),
  "red-5": require("src/assets/cards/red-five.png"),
  "red-6": require("src/assets/cards/red-six.png"),
}
